### ISSUE TITLE
Redundant `unsnoc` in `Utils.Misc`

### ISSUE THREAD

**Issue by andreiburdusa** [octeep/idris2-tls#4]
[`Utils.Misc.Vect.unsnoc`](https://github.com/octeep/idris2-tls/blob/951bef674c41f059d5ccddf568b45588b5dbceee/src/Utils/Misc.idr#L234) is no longer needed because of [this pull request](https://github.com/idris-lang/Idris2/pull/2471). Building idris2-tls gives this error now:
```
Error: While processing right hand side of unsnoc. Ambiguous elaboration. Possible results:
    Utils.Misc.Vect.unsnoc (y Data.Vect.(::) ys)
    Data.Vect.unsnoc (y Data.Vect.(::) ys)
```

I can open a pull request to remove it if the contributors agree.

**Comment by ghost** [comment]
Sure, go ahead. Thanks for pointing it out.
